"""
ISO 3166-1 alpha-3 to UN M49 code mapping
Allows users to enter common 3-letter country codes (USA, GBR, JPN, etc.)
which are then translated to UN numeric codes used by the SDG API
"""

const ISO_TO_UN_CODES = Dict{String, String}(
    # Common countries
    "USA" => "840",  # United States of America
    "GBR" => "826",  # United Kingdom
    "JPN" => "392",  # Japan
    "CHN" => "156",  # China
    "IND" => "356",  # India
    "DEU" => "276",  # Germany
    "FRA" => "250",  # France
    "ITA" => "380",  # Italy
    "ESP" => "724",  # Spain
    "CAN" => "124",  # Canada
    "AUS" => "36",   # Australia
    "BRA" => "76",   # Brazil
    "MEX" => "484",  # Mexico
    "RUS" => "643",  # Russian Federation
    "KOR" => "410",  # Republic of Korea
    "NLD" => "528",  # Netherlands
    "CHE" => "756",  # Switzerland
    "SWE" => "752",  # Sweden
    "NOR" => "578",  # Norway
    "DNK" => "208",  # Denmark
    "FIN" => "246",  # Finland
    "POL" => "616",  # Poland
    "BEL" => "56",   # Belgium
    "AUT" => "40",   # Austria
    "GRC" => "300",  # Greece
    "PRT" => "620",  # Portugal
    "CZE" => "203",  # Czechia
    "HUN" => "348",  # Hungary
    "ROU" => "642",  # Romania
    "NZL" => "554",  # New Zealand
    "IRL" => "372",  # Ireland
    "SGP" => "702",  # Singapore
    "HKG" => "344",  # Hong Kong
    "ISR" => "376",  # Israel
    "SAU" => "682",  # Saudi Arabia
    "ARE" => "784",  # United Arab Emirates
    "TUR" => "792",  # Turkey
    "ZAF" => "710",  # South Africa
    "EGY" => "818",  # Egypt
    "NGA" => "566",  # Nigeria
    "KEN" => "404",  # Kenya
    "ETH" => "231",  # Ethiopia
    "TZA" => "834",  # Tanzania
    "GHA" => "288",  # Ghana
    "UGA" => "800",  # Uganda
    "ARG" => "32",   # Argentina
    "CHL" => "152",  # Chile
    "COL" => "170",  # Colombia
    "PER" => "604",  # Peru
    "VEN" => "862",  # Venezuela
    "THA" => "764",  # Thailand
    "MYS" => "458",  # Malaysia
    "IDN" => "360",  # Indonesia
    "PHL" => "608",  # Philippines
    "VNM" => "704",  # Viet Nam
    "PAK" => "586",  # Pakistan
    "BGD" => "50",   # Bangladesh
    "IRN" => "364",  # Iran
    "IRQ" => "368",  # Iraq
    "AFG" => "4",    # Afghanistan
    "UKR" => "804",  # Ukraine
    "MAR" => "504",  # Morocco
    "DZA" => "12",   # Algeria
    "TUN" => "788",  # Tunisia
    "LBY" => "434",  # Libya
    "SDN" => "729",  # Sudan
    "JOR" => "400",  # Jordan
    "LBN" => "422",  # Lebanon
    "SYR" => "760",  # Syria
    "YEM" => "887",  # Yemen
    "OMN" => "512",  # Oman
    "KWT" => "414",  # Kuwait
    "QAT" => "634",  # Qatar
    "BHR" => "48",   # Bahrain
    "ISL" => "352",  # Iceland
    "LUX" => "442",  # Luxembourg
    "MLT" => "470",  # Malta
    "CYP" => "196",  # Cyprus
    "EST" => "233",  # Estonia
    "LVA" => "428",  # Latvia
    "LTU" => "440",  # Lithuania
    "SVN" => "705",  # Slovenia
    "SVK" => "703",  # Slovakia
    "HRV" => "191",  # Croatia
    "SRB" => "688",  # Serbia
    "BGR" => "100",  # Bulgaria
    "BLR" => "112",  # Belarus
    "KAZ" => "398",  # Kazakhstan
    "UZB" => "860",  # Uzbekistan
    "TKM" => "795",  # Turkmenistan
    "KGZ" => "417",  # Kyrgyzstan
    "TJK" => "762",  # Tajikistan
    "ARM" => "51",   # Armenia
    "GEO" => "268",  # Georgia
    "AZE" => "31",   # Azerbaijan
    "MNG" => "496",  # Mongolia
    "NPL" => "524",  # Nepal
    "LKA" => "144",  # Sri Lanka
    "MMR" => "104",  # Myanmar
    "KHM" => "116",  # Cambodia
    "LAO" => "418",  # Laos
    "BOL" => "68",   # Bolivia
    "PRY" => "600",  # Paraguay
    "URY" => "858",  # Uruguay
    "ECU" => "218",  # Ecuador
    "GTM" => "320",  # Guatemala
    "CUB" => "192",  # Cuba
    "DOM" => "214",  # Dominican Republic
    "HTI" => "332",  # Haiti
    "HND" => "340",  # Honduras
    "NIC" => "558",  # Nicaragua
    "SLV" => "222",  # El Salvador
    "CRI" => "188",  # Costa Rica
    "PAN" => "591",  # Panama
    "JAM" => "388",  # Jamaica
    "TTO" => "780",  # Trinidad and Tobago
    "BHS" => "44",   # Bahamas
    "BRB" => "52",   # Barbados
    "CMR" => "120",  # Cameroon
    "CIV" => "384",  # Côte d'Ivoire
    "SEN" => "686",  # Senegal
    "MLI" => "466",  # Mali
    "BFA" => "854",  # Burkina Faso
    "NER" => "562",  # Niger
    "TCD" => "148",  # Chad
    "COG" => "178",  # Congo
    "COD" => "180",  # Democratic Republic of the Congo
    "AGO" => "24",   # Angola
    "ZMB" => "894",  # Zambia
    "ZWE" => "716",  # Zimbabwe
    "MOZ" => "508",  # Mozambique
    "MDG" => "450",  # Madagascar
    "MWI" => "454",  # Malawi
    "NAM" => "516",  # Namibia
    "BWA" => "72",   # Botswana
    "SWZ" => "748",  # Eswatini
    "LSO" => "426",  # Lesotho
    "MUS" => "480",  # Mauritius
    "RWA" => "646",  # Rwanda
    "BDI" => "108",  # Burundi
    "SOM" => "706",  # Somalia
    "DJI" => "262",  # Djibouti
    "ERI" => "232",  # Eritrea
    "GAB" => "266",  # Gabon
    "GNQ" => "226",  # Equatorial Guinea
    "BEN" => "204",  # Benin
    "TGO" => "768",  # Togo
    "LBR" => "430",  # Liberia
    "SLE" => "694",  # Sierra Leone
    "GIN" => "324",  # Guinea
    "GNB" => "624",  # Guinea-Bissau
    "GMB" => "270",  # Gambia
    "MRT" => "478",  # Mauritania
    "SSD" => "728",  # South Sudan
    "CAF" => "140",  # Central African Republic

    # Additional common codes
    "UK" => "826",   # Alias for United Kingdom
    "US" => "840",   # Alias for United States
    "UAE" => "784"   # Alias for United Arab Emirates
)
